---
abstract: 'adds an attribute name to represent remote naming'
author:
  - 'Caleb Cushing <xenoterracide@gmail.com>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Test::Moose: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300018, CPAN::Meta::Converter version 2.120921'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-RemoteHelper
no_index:
  file:
    - perlcritic.rc
provides:
  MooseX::RemoteHelper:
    file: lib/MooseX/RemoteHelper.pm
    version: 0.001011
  MooseX::RemoteHelper::CompositeSerialization:
    file: lib/MooseX/RemoteHelper/CompositeSerialization.pm
    version: 0.001011
  MooseX::RemoteHelper::Meta::Trait::Attribute:
    file: lib/MooseX/RemoteHelper/Meta/Trait/Attribute.pm
    version: 0.001011
  MooseX::RemoteHelper::Meta::Trait::Class:
    file: lib/MooseX/RemoteHelper/Meta/Trait/Class.pm
    version: 0.001011
  MooseX::RemoteHelper::Meta::Trait::Role:
    file: lib/MooseX/RemoteHelper/Meta/Trait/Role.pm
    version: 0.001011
  MooseX::RemoteHelper::Meta::Trait::Role::ApplicationToClass:
    file: lib/MooseX/RemoteHelper/Meta/Trait/Role/ApplicationToClass.pm
    version: 0.001011
  MooseX::RemoteHelper::Meta::Trait::Role::ApplicationToRole:
    file: lib/MooseX/RemoteHelper/Meta/Trait/Role/ApplicationToRole.pm
    version: 0.001011
  MooseX::RemoteHelper::Meta::Trait::Role::Composite:
    file: lib/MooseX/RemoteHelper/Meta/Trait/Role/Composite.pm
    version: 0.001011
requires:
  Moose: 2
  Moose::Exporter: 0
  Moose::Role: 0
  namespace::autoclean: 0
  perl: 5.008
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/xenoterracide/MooseX-RemoteHelper/issues
  repository: git://github.com/xenoterracide/MooseX-RemoteHelper.git
version: 0.001011
