---
abstract: 'adds an attribute name to represent remote naming'
author:
  - 'Caleb Cushing <xenoterracide@gmail.com>'
build_requires:
  Class::Load: 0.20
  File::Find: 0
  File::Temp: 0
  Test::Method: 0
  Test::Moose: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.120921'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-RemoteHelper
no_index:
  file:
    - perlcritic.rc
provides:
  MooseX::RemoteHelper:
    file: lib/MooseX/RemoteHelper.pm
    version: 0.001013
  MooseX::RemoteHelper::CompositeSerialization:
    file: lib/MooseX/RemoteHelper/CompositeSerialization.pm
    version: 0.001013
  MooseX::RemoteHelper::Meta::Trait::Attribute:
    file: lib/MooseX/RemoteHelper/Meta/Trait/Attribute.pm
    version: 0.001013
  MooseX::RemoteHelper::Meta::Trait::Class:
    file: lib/MooseX/RemoteHelper/Meta/Trait/Class.pm
    version: 0.001013
  MooseX::RemoteHelper::Meta::Trait::Role:
    file: lib/MooseX/RemoteHelper/Meta/Trait/Role.pm
    version: 0.001013
  MooseX::RemoteHelper::Meta::Trait::Role::ApplicationToClass:
    file: lib/MooseX/RemoteHelper/Meta/Trait/Role/ApplicationToClass.pm
    version: 0.001013
  MooseX::RemoteHelper::Meta::Trait::Role::ApplicationToRole:
    file: lib/MooseX/RemoteHelper/Meta/Trait/Role/ApplicationToRole.pm
    version: 0.001013
  MooseX::RemoteHelper::Meta::Trait::Role::Composite:
    file: lib/MooseX/RemoteHelper/Meta/Trait/Role/Composite.pm
    version: 0.001013
  MooseX::RemoteHelper::Types:
    file: lib/MooseX/RemoteHelper/Types.pm
    version: 0.001013
  MooseY::RemoteHelper::MessagePart:
    file: lib/MooseY/RemoteHelper/MessagePart.pm
    version: 0.001013
  MooseY::RemoteHelper::Role::Client:
    file: lib/MooseY/RemoteHelper/Role/Client.pm
    version: 0.001013
requires:
  Moose: 2
  Moose::Exporter: 0
  Moose::Role: 0
  MooseX::Types: 0
  MooseX::Types::Moose: 0
  MooseX::UndefTolerant: 0
  namespace::autoclean: 0
  perl: 5.008
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/xenoterracide/moosex-remotehelper/issues
  homepage: https://metacpan.org/release/MooseX-RemoteHelper
  repository: git://github.com/xenoterracide/moosex-remotehelper.git
version: 0.001013
